# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-24 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_office_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Office',
            new_name='OfficeLocation',
        ),
    ]
