# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-13 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_office_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
