# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-13 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20180513_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
