# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-13 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_office_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
