# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-14 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20180513_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='office',
            name='country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='state',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
