# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
