# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-24 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0004_auto_20180424_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
