# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-13 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0006_office_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
    ]
