# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-13 18:10
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0007_auto_20180513_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
