# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-13 18:17
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0008_office_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
    ]
