# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-05 21:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0012_auto_20180514_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
