# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-05 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0013_office_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='phone',
        ),
    ]
