# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-21 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0014_remove_office_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
