# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-24 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0015_office_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='country',
            new_name='Job_title',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='email',
            new_name='business_email',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='type',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='office',
            name='name',
        ),
        migrations.AddField(
            model_name='office',
            name='company_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
