# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-24 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0016_auto_20180724_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='Job_title',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='business_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='comment',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='company_name',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='office',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='office',
            name='last_name',
        ),
    ]
